server:
  port: 7102  # 后续的其他模块组件，需要通过此配置中心连接github的配置信息

spring:
  application:
    name: zmodule-config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jyz123054/configcenter.git


#  多个配置中心组成集群，注册到配置中心单独的Eureka (zmodule-config-center  7301)中
eureka:
 client:
  service-url:
    defaultZone: http://admin:enjoy@localhost:7301/eureka
 instance:
  prefer-ip-address: true # 在地址栏上使用IP地址进行显示
  instance-id: zmodule-config2