server:
 port: 8090

spring:
 application:
   name: zmodule-provider-users
 zipkin: # Spring Cloud 链路跟踪相关配置
   base-url: http://localhost:8601   # zmodule-sleuth设置的8601端口
   sender:
     type: rabbit   #提交的类型是RABBIT/KAFKA/WEB服务
 sleuth:
   sampler:
     probability: 1.0  #抽样率，默认是0.1，这里为了方便查看设置为1.0  

logging:
  level:
    org.zmodule.mapper: debug

eureka:
  client: # 客户端进行Eureka注册的配置
    service-url:
      defaultZone: http://admin:enjoy@eureka1:7001/eureka,http://admin:enjoy@eureka2:7002/eureka,http://admin:enjoy@eureka3:7003/eureka
  instance:
    instance-id: jyz-provider-users # Status栏显示实例名称id
    prefer-ip-address: true
#    lease-renewal-interval-in-seconds: 2 # 设置心跳的时间间隔（默认是30秒）
#    lease-expiration-duration-in-seconds: 5  # 如果现在超过了5秒的间隔（默认是90秒）



info:
  app.name: zmodule-provider-users
  company.name: enjoy
  build.artifactId: $project.artifactId$
  build.modelVersion: $project.modelVersion$

management:
  endpoints:
    web:
      exposure:
        include: '*'